'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBOCR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  文書ファイルからテキストを読み取ります
        '''
        '''ズームは読み取りに影響しませんが縦横は回転ボタンで調整してください
        '''読み取った部分はマーク表示されます
        '''縦書き横書き混じりの文書の場合、
        '''縦書き文書を横読みすることがあります
        '''マウスドラッグで囲んでその部分だけ読み取りすることもできます
        '''部分読み取りすると結果が別のフォームに表示されます
        '''OKボタンまたはカット＆ペーストで取り込んでください
        '''イメージ保存ボタンで囲んだ部分をファイルに出力することもできます
        '''
        '''&quot;1°&quot;:
        '''オン(黄色)にすると回転ボタンで１度づつ回転されます
        '''少しだけ傾いた画像を読み取るときに使用します
        '''
        '''&quot;読み取り&quot;:
        '''  読み取り結果が下段のテキストフォームに表示されます
        '''  読み取りには多少時間がかかります
        '''
        '''&quot;言語&quot;:
        '''  言語パックを導入すれば日本語以外も選択できます、
        '''  Windows10の場合で英語の言語パックは
        '''    コントロールパネル--&gt;言語および地域--&gt;言語、言語の追加
        '''    追加したら右端のオプション--&gt;言語パックをダウンロードしてインストール
        '''    設定からも&quot;アプリ&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form1() As String
            Get
                Return ResourceManager.GetString("help_Form1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Extract Text from image file.
        '''
        '''Zooming dose not affect extracting,
        '''but you have to adjust up-and-down by Rotate button.
        '''Extracted potions  are marked.
        '''When vertical and horizontal writing are mixed,
        '''vertical writing may be recognized horizontally.
        '''You can specify a portion to be extracted by mouse dragging.
        '''Extracted text partially is shown on another form.
        '''Use OK button or Copy &amp; Paste to take in the text.
        '''ImageSave Button enables to save the portion to image file.
        '''
        '''&quot;1°&quot;:
        '''When On(Yellow), rota [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form1E() As String
            Get
                Return ResourceManager.GetString("help_Form1E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  マウスドラッグで囲んだ部分の読み取りテキストです
        '''
        '''カット＆ペーストでメインフォームに取り込んでください
        '''OKボタンはメインフォームのテキストボックスに送ります、その場合
        '''送り先はメインフォーム上でカーソルをあらかじめ設定しておきます
        '''マウスで反転しておくとその部分が置換されます
        '''
        '''(Form2)                          2017/12/21
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form2() As String
            Get
                Return ResourceManager.GetString("help_Form2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Partially extracted Text in the clipped Box.
        '''
        '''Copy then Paste to Main form.
        '''Or, OK button sends the text to the Main form.
        '''Specify destination range in advance by mouse.
        '''Reversed range will be replaced.
        '''
        '''(Form2E)                          2017/12/21
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form2E() As String
            Get
                Return ResourceManager.GetString("help_Form2E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Icon_sampleVBOCR128() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_sampleVBOCR128", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  |新しいファイル| に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MENU_NEWFILE() As String
            Get
                Return ResourceManager.GetString("MENU_NEWFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  |新規作成| に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MENU_NEWTEXT() As String
            Get
                Return ResourceManager.GetString("MENU_NEWTEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  a に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_NEWFILE() As String
            Get
                Return ResourceManager.GetString("STR_NEWFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み取り結果は空でした に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WARN_EXTRACTED_NULLSTR() As String
            Get
                Return ResourceManager.GetString("WARN_EXTRACTED_NULLSTR", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
