'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBOCR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  (Form1)                          2017/12/10
        '''ファイルからテキストを読み取ります
        '''ズームは読み取りに影響しませんが
        '''縦横は回転ボタンで調整してください
        '''閉じるときは 右上角の X ボタンを押してください
        '''
        '''&quot;読み取り&quot;:
        '''  読み取り結果が下段のテキストフォームに表示されます
        '''  読み取りには多少時間がかかります
        '''
        '''&quot;言語&quot;:
        '''  言語パックを導入すれば日本語以外も選択できます、
        '''  Windows10の場合で英語の言語パックは
        '''    コントロールパネル--&gt;言語および地域--&gt;言語、言語の追加
        '''    追加したら右端のオプション--&gt;言語パックをダウンロードしてインストール
        '''    設定からも&quot;アプリ&quot;,オプション機能の追加、... 光学式文字認識から 
        '''    言語パックのダウンロードができます
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form1() As String
            Get
                Return ResourceManager.GetString("help_Form1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form1E)                2017/12/10
        '''Extract Text from image file.
        '''Zooming dose not affect extracting,
        '''but you have to adjust up-and-down by Rotate button.
        '''Push X button on Upper Right corner.
        '''
        '''&quot;Extract&quot;:
        '''  Extract text from image document.
        '''  This action take a little bit time.
        '''  Extracted text is show to bellow.
        '''
        '''&quot;Language&quot;:
        '''  You can select another Language if LanguagePack is installed.
        '''  On Windows10, install LanguagePack as following.
        '''    ControlPanel--&gt;Language and Locale--&gt;Language, Add La [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form1E() As String
            Get
                Return ResourceManager.GetString("help_Form1E", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
